###
GET http://localhost:5000/api/article/?lang=en&page=3&page_size=8 HTTP/1.1


###
GET http://localhost:5000/api/article/63733950577e41c952f46df4/?lang=en HTTP/1.1


###
GET http://localhost:5000/api/tour/?lang=vi&page=1&page_size=100&continent=europe HTTP/1.1



###
GET http://localhost:5000/api/admin/tour/63735baa79e312fc09f5aa5a HTTP/1.1



###
GET http://localhost:5000/api/admin/tour/6373b81fcb83feb6b27c3d88 HTTP/1.1


### 
GET http://localhost:5000/api/admin/categories?lang=vie HTTP/1.1



### search tour
GET http://localhost:5000/api/tour/search/?lang=vi&page=1&page_size=100&text=heod HTTP/1.1



### search
GET http://localhost:5000/api/article/search/?lang=vi&page=1&page_size=100&text=funixfunix HTTP/1.1